version: '3.1'

services:
  mysqldb:
    image: mysql:8.0-debian
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - "3306:3306"
    expose:
      - "3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=user
      - MYSQL_PASSWORD=p455w0rd
      - MYSQL_DATABASE=cgdb
    networks:
      - cgnet
    volumes:
      - db_vol:/tmp/mysql

networks:
  cgnet:
    driver: bridge

volumes:
  db_vol:
